### ISSUE TITLE
Distorted element in Two effects

### ISSUE THREAD

**Issue by sabriunal** [nate-xyz/conjure#11]
Some elements seems distorted in two effects.

Statistic

![1](https://user-images.githubusercontent.com/6218679/226597105-12e2c3e6-8398-49f2-b8cc-fd349ea2e673.png)

Quantize

![2](https://user-images.githubusercontent.com/6218679/226597100-1a00e148-b90e-456f-9241-baab8d59704b.png)

**Comment by nate-xyz** [comment]
I believe I fixed this in my last commit, just need to push to the flathub repo. Would you mind testing to confirm?

**Comment by sabriunal** [comment]
Seems fixed in main branch. Thanks.
