### ISSUE TITLE
Unused base_name in window.py

### ISSUE THREAD

**Issue by sabriunal** [nate-xyz/conjure#14]
Hi, there is a papercut here. base_name defined but unused. 

```python
    def open_image_toast(self, uri):
        base_name = html.escape(os.path.basename(uri))
        self.add_success_toast(_("Opened image:"), os.path.basename(uri))

```

Source: https://github.com/nate-xyz/conjure/blob/main/conjure/window.py#L106-L107

**Comment by nate-xyz** [comment]
https://github.com/nate-xyz/conjure/commit/43f1001719d8ec3c64dbda7a495851f724150301
